language: python
python:
  - 3.5
  - 3.6
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get -qq update
  - sudo apt-get install gfortran
install:
  - pip install -r requirements.txt
  - pip install pytest
  - git clone https://github.com/Axelrod-Python/TourExec.git /tmp/TourExec
  - cd /tmp/TourExec
  - make install
script:
    - pytest
